version: '2.1'

services:
  
  # ------------------------------------------------------------------------------------
  # N3uron
  # ------------------------------------------------------------------------------------
  n3uron:
    image: n3uronhub/n3uron:v1.21.7
    ports:
      - 80:8003 # HTTP WebUI for balena's Public Device URL feature
      - 8003:8003 # HTTP WebUI
      - 8443:8443 # HTTPS WebUI
      - 8004:8004 # HTTP WebVision
      - 8444:8444 # HTTPS WebVision
      - 3001:3001 # Inbound Links
    environment:
      - HOSTNAME=balena-historian
    volumes:
      - config:/opt/n3uron/config
      - data:/opt/n3uron/data
      - licenses:/opt/n3uron/licenses
      - log:/opt/n3uron/log
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
        io.balena.features.balena-socket: '1'
        io.balena.features.kernel-modules: '1'
        io.balena.features.firmware: '1'
    devices:
        - "/dev/ttySC0:/dev/ttySC0"
        - "/dev/ttySC1:/dev/ttySC1"
        - "/dev/ttySC2:/dev/ttySC2"
        - "/dev/ttySC3:/dev/ttySC3"
    restart: unless-stopped

  # ------------------------------------------------------------------------------------
  # Industrial Shields PLC for RPi
  # ------------------------------------------------------------------------------------
  industrial-shields:
    build: ./industrial-shields 
    privileged: true
    restart: unless-stopped
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
        io.balena.features.balena-socket: '1'
        io.balena.features.kernel-modules: '1'
        io.balena.features.firmware: '1'
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"
        - "/dev/ttyUSB0:/dev/ttyUSB0"
        - "/dev/ttySC0:/dev/ttySC0"
        - "/dev/ttySC1:/dev/ttySC1"
        - "/dev/ttySC2:/dev/ttySC2"
        - "/dev/ttySC3:/dev/ttySC3"

volumes:
  config:
  data:
  licenses:
  log:
  mongo_data:
